name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
        # Auto-install webpack-cli tanpa prompt
        echo "yes" | npx webpack || true
        npm install -D webpack-cli
        
    - name: Build project
      run: npm run build
      
    - name: Fix audit issues
      run: npm audit fix --force
      
